### ISSUE TITLE
Get error on start

### ISSUE THREAD

**Issue by helish88** [oakgary/RedScrap#1]
Hello! I write node scraper.js and I get an error
![image](https://user-images.githubusercontent.com/52331802/65419589-a5d75200-de07-11e9-93cf-4350c6be96cb.png)

**Comment by oakgary** [comment]
You have an error in your config.json, probably a comma at the end.

This is how a valid config.json could look like:
```json
{
    "webhook": "https://discordapp.com/api/webhooks/{webhook.id}/{webhook.token}",
    "sort": "top",
    "time": "day",
    "itemsPerPage": 10,
    "amountOfPages": 1,
    "subreddits": ["funny","videos","gifs"],
    "interval": 1000
}
```

**Comment by helish88** [comment]
![image](https://user-images.githubusercontent.com/52331802/65483694-d2da4200-dea5-11e9-96d2-ef9efde0e2ce.png)

**Comment by helish88** [comment]
I think bcz I wrote only 2 subreddits

**Comment by helish88** [comment]
thx.it work!

**Comment by helish88** [comment]
![image](https://user-images.githubusercontent.com/52331802/65494217-0d9ba480-debd-11e9-86d8-abeb54b657ae.png)
videos in embed message not displayed.

**Comment by oakgary** [comment]
You can have as many subreddits as you want, but they have to be in an array.
Also if you use it for discord you can safely put the interval down to 2000. It does not have to be 60000.

If a video embed does not work it is because discord does not support it. 
Some work, some do not. 🙃

**Comment by helish88** [comment]
thx man.
